<div class="bs-header" id="content">
    <div class="container">
        <h1>Zend\Together</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="hidden-print affix-top" role="complementary">
                <?php echo $this->navigation('Navigation')->menu(); ?>
            </div>
        </div>
        <div class="col-md9" role="main">
            <?php echo $content;?>
        </div>
    </div>
</div>